stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: "mkdir -p /root/.m2 \nmvn clean install"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      registry: 47.107.157.185:31803
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: http://sonatype-nexus-service.sonatype-nexus:8083
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
